<?php \Controllers\Page::loadFragments("header");?>
<section id="content">

<h1>Homepage</h1>

    <h3>Le MVC wiki better than lorem ipsum</h3>
    <p>Le <a href="https://fr.wikipedia.org/wiki/Patron_de_conception" title="Patron de conception">patron</a> d'architecture logicielle <b>modèle-vue-contrôleur</b> (en abrégé <b>MVC</b>, en anglais <span class="lang-en" lang="en" xml:lang="en"><i>model-view-controller</i></span>), tout comme les patrons <a href="https://fr.wikipedia.org/wiki/Mod%C3%A8le-vue-pr%C3%A9sentation" title="Modèle-vue-présentation">modèle-vue-présentation</a> ou <a href="https://fr.wikipedia.org/wiki/Pr%C3%A9sentation,_abstraction,_contr%C3%B4le" title="Présentation, abstraction, contrôle">présentation, abstraction, contrôle</a>, est un modèle destiné à répondre aux besoins des applications interactives en séparant les problématiques liées aux différents composants au sein de leur architecture respective.</p>
<iframe class="iframe_for_fun" src="https://fr.wikipedia.org/wiki/Mod%C3%A8le-vue-contr%C3%B4leur"></iframe>
</section>

<?php \Controllers\Page::loadFragments("footer");?>
